/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { TAgentType } from "engine-wasm";

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh;
    Head1: THREE.Mesh;
    ArmLeft1: THREE.Mesh;
    ArmRight1: THREE.Mesh;
    LegLeft1: THREE.Mesh;
    LegRight1: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
};

const ModelLocation: Record<TAgentType[0], string> = {
  "Man1": "man1.gltf",
  "Man2": "man2.gltf",
};

type Props = {
  modelType: keyof typeof ModelLocation;
} & JSX.IntrinsicElements["group"];

export const Model = ({ modelType, ...props }: Props) => {
  const group = useRef<THREE.Group>();
  const { nodes } = useGLTF(ModelLocation[modelType]) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body1.geometry}
        material={nodes.Body1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head1.geometry}
        material={nodes.Head1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArmLeft1.geometry}
        material={nodes.ArmLeft1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArmRight1.geometry}
        material={nodes.ArmRight1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LegLeft1.geometry}
        material={nodes.LegLeft1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LegRight1.geometry}
        material={nodes.LegRight1.material}
      />
    </group>
  );
};

useGLTF.preload(ModelLocation["Man1"]);
useGLTF.preload(ModelLocation["Man2"]);
