/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh;
    Head1: THREE.Mesh;
    ArmLeft1: THREE.Mesh;
    ArmRight1: THREE.Mesh;
    LegLeft1: THREE.Mesh;
    LegRight1: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
};

export enum ModelType {
  Man1 = "man1.gltf",
  Man2 = "man2.gltf",
  // Woman1 = "woman1.gltf",
  // Woman2 = "woman2.gltf",
}

type Props = { modelType: keyof typeof ModelType } & JSX.IntrinsicElements["group"];

export const Model = ({ modelType, ...props }: Props) => {
  const group = useRef<THREE.Group>();
  const { nodes } = useGLTF(ModelType[modelType]) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body1.geometry}
        material={nodes.Body1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head1.geometry}
        material={nodes.Head1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArmLeft1.geometry}
        material={nodes.ArmLeft1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArmRight1.geometry}
        material={nodes.ArmRight1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LegLeft1.geometry}
        material={nodes.LegLeft1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LegRight1.geometry}
        material={nodes.LegRight1.material}
      />
    </group>
  );
};

useGLTF.preload("man1.gltf");
useGLTF.preload("man2.gltf");
// useGLTF.preload("/assets/woman1.gltf");
// useGLTF.preload("/assets/woman2.gltf");
